vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        quai_images:
            uri_prefix: /images/quai_images
            upload_destination: '%kernel.project_dir%/public/images/quai_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
