vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        quai_images:
            uri_prefix: '%quai_images%'
            upload_destination: '%kernel.project_dir%/public%quai_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true
